- name: manageiq-apb playbook to deprovision the application
  hosts: localhost
  vars:
    state: absent
  gather_facts: false
  connection: local
  roles:
  - role: ansible.kubernetes-modules
    install_python_requirements: no
  - role: manageiq-apb
    playbook_debug: false
